import { CardItemType, RentType } from '../shared-types';

export const cards: CardItemType[] = [
  {
    id: '1',
    title: 'The Joshua Tree House',
    type: 'house' as RentType,
    price: 555,
    previewImage: '/public/img/1.jpeg',
    city: 'Paris',
    isFavorite: false,
    isPremium: false,
    rating: 1.4,
  },
  {
    id: '2',
    title: 'Loft Studio in the Central Area',
    type: 'apartment' as RentType,
    price: 462,
    previewImage: '/public/img/2.jpeg',
    city: 'Paris',
    isFavorite: false,
    isPremium: false,
    rating: 2.4,
  },
  {
    id: '3',
    title: 'Waterfront with extraordinary view',
    type: 'house' as RentType,
    price: 169,
    previewImage: '/public/img/3.jpeg',
    city: 'Paris',
    isFavorite: false,
    isPremium: false,
    rating: 3.1,
  },
  {
    id: '4',
    title: 'House in countryside',
    type: 'room' as RentType,
    price: 233,
    previewImage: '/public/img/4.jpeg',
    city: 'Paris',
    isFavorite: false,
    isPremium: true,
    rating: 1.1,
  },
  {
    id: '5',
    title: 'Amazing and Extremely Central Flat',
    type: 'house' as RentType,
    price: 243,
    previewImage: '/public/img/5.jpeg',
    city: 'Paris',
    isFavorite: false,
    isPremium: true,
    rating: 1.3,
  },
];
